---
- name: install tomcat server
  hosts: 35.184.87.35 
  become: true
  tasks:
  - name: install java
    apt:
      name: openjdk-8-jdk
      state: latest
  - name: download tomcat server
    get_url:
      url: http://mirror.cc.columbia.edu/pub/software/apache/tomcat/tomcat-8/v8.5.47/bin/apache-tomcat-8.5.47.tar.gz
      dest: /usr/local
  - name: extract tomcat
    unarchive:
      src: /usr/local/apache-tomcat-8.5.47.tar.gz
      dest: /usr/local
      remote_src: yes
  - name: start tomcat
    shell: /usr/local/apache-tomcat-8.5.47/bin/startup.sh

